services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    restart: unless-stopped
    command: >
      sh -c "echo '🔧 Initializing database...' &&
             alembic upgrade head &&
             echo '👤 Creating admin user...' &&
             python app/scripts/create_admin.py &&
             echo '🚀 Starting application...' &&
             uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
