"""added last_location_airport and next_destination airprt

Revision ID: 7d8b97bc6ed8
Revises: 6c2472866cad
Create Date: 2025-09-25 13:52:06.215511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d8b97bc6ed8'
down_revision: Union[str, None] = '6c2472866cad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
